### ISSUE TITLE
The Planetary Network Connector does not allow you to properly ssh from Windows 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/planetary_network_desktop_client#46]
### What happened?

It is currently incredibly difficult to SSH a workload with a planetary network address from windows when using putty or wsl, neither of these applications appear to be able to access the planetary network with the connector running 

- wsl makes sense, but there isn’t a connector for that 
    - you can connect from wsl by following this tutorial 
 https://forum.threefold.io/t/howto-connect-to-planetary-network-on-wsl2/3511
 
- putty should work since it’s an application running in the base os alongside the connector but it doesn’t. Installing yggdrasil and configuring it does allow putty to work though. 

Replicate: 

- Install the network connector in windows
- Try to ssh a workload with a planetary address. 

My results: 
Connection failed on all attempts

### What did you expect?

Ability to use the planetary network from windows.

**Comment by A-Harby** [comment]
I installed wsl on a windows 10 using default ubuntu (just run `wsl --install`), and then I followed the instructions from https://forum.threefold.io/t/howto-connect-to-planetary-network-on-wsl2/3511 to clone and install Planetary Network ygg.

In the last step to test it, I used the mentioned command `sudo yggdrasil -useconffile /etc/yggdrasil.conf` but all the connection failed.
![image](https://github.com/threefoldtech/planetary_network_desktop_client/assets/109473873/2ac1f22c-ea17-46a0-b6b4-2a9da9ecab2b)
